name: Continuous Deployment
on:
  push:
    branches:
      - production
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: burnett01/rsync-deployments@7.0.2
        name: Deploy with rsync
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /var/www/server
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
      - uses: appleboy/ssh-action@master
        name: Execute remote commands
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            cd /var/www/server && \
            npm ci && \
            pm2 restart index && \
            sudo nginx -t && \
            sudo systemctl restart nginx
