name: Continuous Deployment

on:
  push:
    branches:
      - production
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Test SSH Connection
        run: |
          echo "${{ secrets.REMOTE_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "echo 'SSH connection successful'"
      - uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: ./
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: /var/www/server
      - uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}
          privateKey: ${{ secrets.REMOTE_KEY }}
          command: |
            cd /var/www/server/
            npm ci
            pm2 restart index
            sudo nginx -t
            sudo systemctl restart nginx
